spring:
  config:
    import: optional:file:.env[.properties]

  application:
    name: ai-code-review-system

  datasource:
    url: jdbc:postgresql://localhost:5432/ai_code_review
    username: harsh
    password: ""

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

  data:
    redis:
      host: localhost
      port: 6379

openrouter:
  api-key: ${OPENROUTER_API_KEY}
  model: nvidia/nemotron-nano-9b-v2:free

github:
  token: ${GITHUB_TOKEN}